name: kryptie
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^9.5.0
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_snake_navigationbar: ^0.6.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.2
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hugeicons: ^0.0.7
  icons_plus: ^5.0.0
  intl: ^0.19.0
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  objectbox: ^4.0.3
  
  objectbox_flutter_libs: ^4.0.3
  path: ^1.9.0
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  restart_app: ^1.3.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  
  objectbox_generator: ^4.0.3
  very_good_analysis: ^6.0.0


objectbox:
  output_dir: shared/helpers/objectbox
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - .env